### ISSUE TITLE
[jr3pci4channelYarp] IOCTL1_JR3_GET_FULL_SCALES on 2 and 3

### ISSUE THREAD

**Issue by jgvictores** [LoliPinel/LoliRepo#1]
In jr3pci4channelYarp, it would seem logic to:
- https://github.com/lpinel/LoliRepo/blob/55b101c9fd2a95f40b7d01b7e90f43af87d8bab3/TFM/jr3Yarp/jr3pci4channelYarp/main.cpp#L59 ->IOCTL2_JR3_GET_FULL_SCALES
-  https://github.com/lpinel/LoliRepo/blob/55b101c9fd2a95f40b7d01b7e90f43af87d8bab3/TFM/jr3Yarp/jr3pci4channelYarp/main.cpp#L61 -> IOCTL3_JR3_GET_FULL_SCALES

Could I please have anybody's opinion on this?

**Comment by lpinel** [comment]
It is corrected in branch master. See 45f0da70d8a266dd72bbb23f414c8e0da9bb0a3f

**Comment by jgvictores** [comment]
Ok, thanks!
